name: Deploy to Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: 25135783-6ddc-4c53-8e27-1b74487ef82a
        run: |
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --detach
